_BASE_: "../base.yaml"

DATASETS:
  TRAIN: ("synmap_skeleton_ms_train", "synmap_osm_ms_train", "synmap_skeleton_train", "synmap_osm_train", "synthtext22_poly_train", "synthtext12_poly_train",)
  TEST: ("weinman_test","rumsey_test",)

MODEL:
  BATEXT:
    VOC_SIZE: 96
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    VOC_SIZE: 96
    INFERENCE_TH_TEST: 0.3
    LOSS:
      POINT_TEXT_WEIGHT: 8.0
      
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (340000,)
  MAX_ITER: 440000
  CHECKPOINT_PERIOD: 10000
  
TEST:
  EVAL_PERIOD: 10000
  
OUTPUT_DIR: "output/pretrain_en_synthtext_synthmap_tt_ic_mlt"
