_BASE_: "../base.yaml"

DATASETS:
  TRAIN: ("synthtext1_coord_train", "synthtext2_coord_train", "map_coord_train", "map_coord_train1")
  TEST: ()

MODEL:
  BATEXT:
    VOC_SIZE: 14
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    VOC_SIZE: 14
    INFERENCE_TH_TEST: 0.3
    LOSS:
      POINT_TEXT_WEIGHT: 8.0

SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 1e-4
  LR_BACKBONE: 1e-5
  WARMUP_ITERS: 0
  STEPS: (240000,)
  MAX_ITER: 340000
  CHECKPOINT_PERIOD: 10000
  
TEST:
  EVAL_PERIOD: 100000
  
OUTPUT_DIR: "output/pretrain_coord_synthtext_map"
