_BASE_: "../Base-PALEJUN.yaml"
MODEL:
  TRANSFORMER:
    NUM_CHARS: 25
    USE_POLYGON: True
    NUM_CTRL_POINTS: 16
    LOSS:
      POINT_TEXT_WEIGHT: 8.0
TEST:
  USE_LEXICON: False
  LEXICON_TYPE: 1
INPUT:
  MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024, 1200, 1400)
  MAX_SIZE_TRAIN: 2333
  MIN_SIZE_TEST: 1600
  MAX_SIZE_TEST: 4000
  CROP:
    ENABLED: True
    CROP_INSTANCE: False
    SIZE: [0.3, 0.3]
  FORMAT: "RGB"