_BASE_: "base.yaml"

DATASETS:
  TRAIN: ()
  TEST: ()

MODEL:
  BATEXT:
    VOC_SIZE: 14
  WEIGHTS: "/data/weiweidu/mapkurator/spotter-v2/weights/model_v2_coord.pth"
  RESNETS:
    DEPTH: 50
  TRANSFORMER:
    VOC_SIZE: 14
    INFERENCE_TH_TEST: 0.3
    
INPUT:
  HFLIP_TRAIN: False
  MIN_SIZE_TEST: 1600
  MAX_SIZE_TEST: 1892
  
TEST:
  USE_LEXICON: False
  LEXICON_TYPE: 1
    
OUTPUT_DIR: ""

